local p=game:GetService("Players")local h=game:GetService("HttpService")local pl=p.LocalPlayer local pg=pl:WaitForChild("PlayerGui")
local sg=Instance.new("ScreenGui")sg.Name="ShimmyLoader"sg.ResetOnSpawn=false sg.Parent=pg
local mf=Instance.new("Frame")mf.Size=UDim2.new(0,500,0,600)mf.Position=UDim2.new(0.5,-250,0.5,-300)mf.BackgroundColor3=Color3.fromRGB(0,0,0)mf.Parent=sg
local t=Instance.new("TextLabel")t.Size=UDim2.new(1,0,0,50)t.BackgroundTransparency=1 t.Text="Shimmy Loader"t.TextColor3=Color3.fromRGB(255,255,255)t.TextScaled=true t.Parent=mf
local ins={}for i=1,10 do local b=Instance.new("TextBox")b.Size=UDim2.new(1,-20,0,40)b.Position=UDim2.new(0,10,0,60+(i-1)*45)b.PlaceholderText="Game "..i.." (e.g. Prison Life)"b.BackgroundColor3=Color3.fromRGB(40,40,40)b.TextColor3=Color3.fromRGB(255,255,255)b.TextScaled=true b.Parent=mf ins[i]=b end
local gb=Instance.new("TextButton")gb.Size=UDim2.new(1,-20,0,50)gb.Position=UDim2.new(0,10,1,-60)gb.BackgroundColor3=Color3.fromRGB(0,150,0)gb.Text="Generate Loadout"gb.TextColor3=Color3.fromRGB(255,255,255)gb.TextScaled=true gb.Parent=mf
local lf=Instance.new("Frame")lf.Size=UDim2.new(0,500,0,600)lf.Position=UDim2.new(0.5,-250,0.5,-300)lf.BackgroundColor3=Color3.fromRGB(0,0,0)lf.Visible=false lf.Parent=sg
local lt=Instance.new("TextLabel")lt.Size=UDim2.new(1,0,0,50)lt.BackgroundTransparency=1 lt.Text="Generated Loadout - Click Exec"lt.TextColor3=Color3.fromRGB(255,255,255)lt.TextScaled=true lt.Parent=lf
local slots={}local gnames={}
local function fetch(g)local s,e=pcall(function()local u="https://scriptblox.com/api/script/search?q="..h:UrlEncode(g).."&max=5&sortBy=views&order=desc"local d=h:GetAsync(u)local j=h:JSONDecode(d)if j.result and j.result.scripts and #j.result.scripts>0 then local b=j.result.scripts[1]local r="https://scriptblox.com/api/script/raw/"..b._id return h:GetAsync(r)end end)return s and e or nil end
gb.MouseButton1Click:Connect(function()gnames={}for i=1,10 do local n=ins[i].Text:match("^%s*(.-)%s*$")gnames[i]=n\~=""and n or("Game "..i)end mf.Visible=false lf.Visible=true for _,s in ipairs(slots)do s:Destroy()end slots={}for i=1,10 do local sl=Instance.new("Frame")sl.Size=UDim2.new(1,-20,0,50)sl.Position=UDim2.new(0,10,0,60+(i-1)*55)sl.BackgroundColor3=Color3.fromRGB(30,30,30)sl.Parent=lf local nl=Instance.new("TextLabel")nl.Size=UDim2.new(0,40,1,0)nl.BackgroundTransparency=1 nl.Text=i.."."nl.TextColor3=Color3.fromRGB(255,255,255)nl.TextScaled=true nl.Parent=sl local gl=Instance.new("TextLabel")gl.Size=UDim2.new(0.6,-50,1,0)gl.Position=UDim2.new(0,50,0,0)gl.BackgroundTransparency=1 gl.Text=gnames[i]gl.TextColor3=Color3.fromRGB(200,200,200)gl.TextScaled=true gl.TextXAlignment=Enum.TextXAlignment.Left gl.Parent=sl local eb=Instance.new("TextButton")eb.Size=UDim2.new(0,80,0.8,0)eb.Position=UDim2.new(1,-90,0.1,0)eb.BackgroundColor3=Color3.fromRGB(0,120,255)eb.Text="Exec"eb.TextColor3=Color3.fromRGB(255,255,255)eb.Parent=sl eb.MouseButton1Click:Connect(function()eb.Text="Fetching..."local c=fetch(gnames[i])if c then local ok,err=pcall(function()loadstring(c)()end)eb.Text=ok and "Executed!" or "Error"else eb.Text="Not Found"end wait(2)eb.Text="Exec"end)table.insert(slots,sl)end end)
local cb=Instance.new("TextButton")cb.Size=UDim2.new(0,40,0,40)cb.Position=UDim2.new(1,-45,0,5)cb.BackgroundColor3=Color3.fromRGB(180,0,0)cb.Text="X"cb.TextColor3=Color3.fromRGB(255,255,255)cb.Parent=lf cb.MouseButton1Click:Connect(function()sg:Destroy()end)
